export const RoutePath = Object.freeze({
  Home: '/',
  Welcome: '/welcome',
  Profile: '/profile',
  Login: '/login',
  Register: '/register',
  RegisterEmailVerification: '/register/email-verification',
  RegisterConnectWallet: '/register/connect-wallet',
  Discover: '/discover',
  DiscoverComics: '/discover/comics',
  DiscoverComicIssues: '/discover/comic-issues',
  DiscoverCreators: '/discover/creators',
  Library: '/library',
  OwnedAssets: (slug: string) => `/library/${slug}`,
  Mint: (id: string | number) => `/mint/${id}`,
  Claim: (id: string | number) => `/claim/${id}`,
  Comic: (comicSlug: string) => `/comic/${comicSlug}`,
  ComicRead: (comicSlug: string) => `/comic/${comicSlug}/read`,
  ComicIssue: (comicIssueId: string | number) => `/comic-issue/${comicIssueId}`,
  ReadComicIssue: (comicIssueId: string | number) => `/comic-issue/${comicIssueId}/read`,
  Creator: (creatorSlug: string) => `/creator/${creatorSlug}`,
  PrivacyPolicy: '/privacy-policy',
  Invest: '/invest',
  InvestDetails: (slug: string) => `/invest/${slug}`,
  Payout: (slug: string) => `/payout/${slug}`,
})
