export const TWITTER_LINK = 'https://x.com/dReaderApp'
export const DISCORD_LINK = 'https://discord.gg/PBW84NaEE2'
export const GOOGLE_PLAY_LINK = 'https://play.google.com/store/apps/details?id=io.app.dreader'
export const INSTAGRAM_LINK = 'https://www.instagram.com/d_reader_app'
export const TENSOR_LINK = 'https://www.tensor.trade/creator/dreader'
export const GOOGLE_PLAY_APP_LINK = 'https://play.google.com/store/apps/details?id=io.app.dreader'
export const LINKTREE_LINK = 'https://dreader.io/links'
export const DPUBLISHER_LINK = 'https://dpublisher.app'
